---
title: "Optional tutorial: applying MOFA to integrate multi-omics data from the BeatAML study "
author: 
  name: "Junyan Lu"
  affiliation: "University Hospital Heidelberg, Germany"
  email: "junyan.lu@uni-heidelberg.de"
date: "July 2026"
format: 
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
---


# Introduction

In this optional tutorial, you are encouraged to apply MOFA, based on what you've learned in the main tutorial, to integrate and interpret a multi-omic dataset from the BeatAML study: https://www.cancer.gov/about-nci/organization/ccg/blog/2019/beataml. The datasets from BeatAML cohort are very similar to those from the CLL cohort. In this practical session, we will use the drug screen, mRNA expression and mutation data from this study. The pre-processed data can be found in the "processed" folder.   

# Specific tasks

**Task 1: Format the pre-processed omics data and prepare input for MOFA.**. You have the freedom to choose your own ways of formatting the omics data, as long as they make statistical sense and follow the requirements of MOFA model. If you are not sure, please consult the trainers.  

**Task 2: Setup and train MOFA model.** Don't forget to choose an appropriate likelihood for each of the data modalities! 

**Task 3: Visualise the MOFA training results.** You can use the pre-built functions within MOFA2 package or your own codes to explore the results of MOFA training. You are encouraged to answers questions like: How to get the factor scores for each sample? Are those factor scores correlate with each other? How much variance can each factor explain for each view?  

**Task 4: Interpreting the MOFA training results.** Please use the pre-built functions within MOFA2 package or your own codes to answer the below questions:  
- How to identify interesting factors from MOFA results?   
- How to understanding the biology behind the MOFA factors?  
- How those results can be used for clinical or biological applications?  

